#!/bin/sh

cd tools

echo "\n=== Compiling documentation ===\n"
if [ ! -d ../docs ]
then
  mkdir ../docs
fi
cp overview.txt DPSO_Logo.png ../Addons

perl natural_docs/NaturalDocs -r -i "../Addons" -xi "../Addons/Main/Functions/AIS" -o HTML "../docs" -p "DPSO-fundamentals" -s Default -s DPSO
rm ../Addons/overview.txt
rm ../Addons/DPSO_Logo.png
